### ISSUE TITLE
Max transaction number

### ISSUE THREAD

**Issue by jdetychey** [danny-wu/MultiSigWallet#1]
it seems like the contract can not handle more than 2^256 - 1 transactions : 

```   
 function addTransaction(address destination, uint value, bytes data)
        internal
        notNull(destination)
        returns (uint transactionId)
    {
        transactionId = transactionCount;
        transactions[transactionId] = Transaction({
            destination: destination,
            value: value,
            data: data,
            executed: false
        });
        transactionCount += 1;
        Submission(transactionId);
    }

``` 
The transaction 2^256 will likely create an overflow on transactionCount and reset it to 0 while receiving transactionId 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.
The transaction 2^256+1 will likely have transactionId = 0 and overwrite the struct : 
``` 

    struct Transaction {
        address destination;
        uint value;
        bytes data;
        bool executed;
    }

``` 
with malicious destination and value. Since transactionId = 0 might be mapped to a sufficiently confirmed transaction, the malicious owner could have it executed right away.

**Comment by danny-wu** [comment]
Thank you Jerome.

I believe creating 2^256 transactions requires more computation power than brute forcing every single private key in Ethereum; in addition a hash collision would probably happen on ETH.

Please feel free to reopen if there are any practical security concerns with this 2^256 overflow.

**Comment by jdetychey** [comment]
Indeed, you are right on the computation power needed but I couldn t find any other potential bugs in your contract ^/^. Your approach really limits the vector of attacks
